In [2]:
#date:30/05/2026
#adding elements of lists
a=[1,2,3]
b=[2,4,3]
res=[]
for i in range(len(a)):
    res.append(a[i]+b[i])
print(res)


[3, 6, 6]


In [16]:
import numpy
arr=numpy.array([1.2,2.3,3.4,4.60,5.6])
ar1=numpy.array([[1,2,3],[3,4,5]])
ar2=numpy.array([[[1,2,3],[2,3,4],[4,5,6]]])
print(arr)
print(ar1)
print(ar2)
print(arr.shape)
print(ar1.shape)
print(arr.ndim)
print(ar1.ndim)
print(ar2.ndim)
print(ar1.size)
print(arr.dtype)

[1.2 2.3 3.4 4.6 5.6]
[[1 2 3]
 [3 4 5]]
[[[1 2 3]
  [2 3 4]
  [4 5 6]]]
(5,)
(2, 3)
1
2
3
6
float64


In [36]:
#array creation in numpy
'''
1 np.array() - converts list or tuple into array
2 np.zeros() - creating a array with initial value zero
3 np.ones() -  creating a array with initial value one
4 np.arange() - works like range() function
    syntax  
    np.arange(start,stop,step)
'''
import numpy as n
a=n.array([1,3,2,4,5])
b=n.zeros(5)
print(a)
print(b)
c=n.zeros((2,2))
print(c)
d=n.ones(2)
print(d)
e=n.ones((2,4))
print(e)
print(n.arange(1,10,2))                 # splits elements into 2 intervals
print(n.linspace(1,20,5))               # splits into 5 equal elements
print(n.random.rand(5))                 # print values form 0 to 1
print(n.random.randint(-100,100,20))    # print values with the range and no of elements specified in right side
print(n.random.randn(5))                # prints random decimal,can be positive and negative


[1 3 2 4 5]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 3 5 7 9]
[ 1.    5.75 10.5  15.25 20.  ]
[0.14614576 0.18999333 0.72239394 0.97849718 0.21727915]
[ 65 -78 -11 -41  -7 -63 -93 -79  84 -39  32  79  12  65 -22 -93  47 -26
  94 -89]
[-1.11628297  1.25632495 -0.58664199  0.44722447  1.89439676]


In [45]:
#Indexing&slicing
'''
used for
1 accessing data
2 extract data
3 modify data
numpy supports
1 1D-indexing
2 2D-indexing
3 1D-slicing
4 2D-slicing
5 Boolean indexing
6 Fancy indexing
slicing syntax
array_name(start:stop:step)
'''
import numpy as n
a=n.array([10,20,30,40,50])
print(a[1])
print(a[2:5])
print(a[:4])
print(a[:-1])
b=n.array([[1,2,3],[2,5,6],[4,7,8]])
print(b[1][2])
print(b[1])
print(b[:,-1])


20
[30 40 50]
[10 20 30 40]
[10 20 30 40]
6
[2 5 6]
[3 6 8]


In [52]:
#Boolean Indexing -use to filter values based on conditions
#Fancy Indexing -use to print specific multipe values from the array
import numpy as n
a=n.array([10,20,30,40,50])
print(a[a>25])             # Boolean Indexing
print(a[a%2==0])           # Boolean Indexing
print(a[[0,4,2,3]])        # Fancy Indexing
a[3]=10
print(a)

[30 40 50]
[10 20 30 40 50]
[10 50 30 40]
[10 20 30 10 50]


In [67]:
# Mathematical Operation in numpy
'''
1 Element wise operation
2 Broadcasting - it allows numpy to perform operation between array of different shapes
Types:
    1-Scalar Broadcasting
    2-2D Broadcasting
    3-Row Broadcasting
        rule:two array shoud have same dimensions,which means both array should have same no of rows 
3 Matrix Operation - 
'''
import numpy as n
a=n.array([10,20,30])
b=n.array([[1,2,3],[2,3,4]])
print(a+5)                   # Scalar Broadcasting
print(b+10)                  # 2D  Broadcasting
print(b+a)                   # Row Broadcasting
# Matrix Oerations
c1=n.array([[1,2],[3,4]])
c2=n.array([[2,3],[8,9]])
print(a*b)
print(np.matmul(c1,c2))      # or print(np.dot(c1,c2)) or print(a@b)
print(a.T)                   #Transpose(row into colunm & viceversa)


[15 25 35]
[[11 12 13]
 [12 13 14]]
[[11 22 33]
 [12 23 34]]
[[ 10  40  90]
 [ 20  60 120]]
[[18 21]
 [38 45]]
[10 20 30]


In [73]:
# Universal Mathematical Function
import numpy as n
a1=n.array([4,9,16])
print(n.sqrt(a1))
a2=n.array([-1,-2,-4])
print(n.abs(a2))
print(n.log(a))
print(n.exp(a1))
# Round Off Functions
print(n.round(a1,2))
print(n.floor(a1))
print(n.ceil(a1))


[2. 3. 4.]
[1 2 4]
[2.30258509 2.99573227 3.40119738]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 4  9 16]
[ 4  9 16]
[ 4  9 16]


In [82]:
#Statistical Functions
'''
used to:
    1 Data Analysing
    2 to find average
    3 Spread of data
    4 find relationship between variable
1 Mean()-find average
2 Median()-to find mid value afer sorting
3 std deviation()-how far data spread from mean
    small std-data close to mean
    large std-data spread widely
4 coorelation-relationship between variable
    positve= +1
    negative= -1
    no coorelation
5.Persentile
'''
import numpy as n
a=n.array([10,2,3,30,50])
print(n.mean(a))
print(n.median(a))
print(n.std(a))
print(n.min(a))
print(n.max(a))
print(n.percentile(a,25))
print(n.var(a))
print(n.argmin(a))
print(n.argmax(a))
b=n.array([10,2,3,30,50])
c=n.array([20,12,13,40,60])
print(n.corrcoef(b,c))

# Aggregate Function
d=n.array([[2,3,4],[2,4,5]])
print(n.sum(d))
print(n.sum(d,axis=1))
print(n.sum(d,axis=0))

19.0
10.0
18.482424083436676
2
50
3.0
341.6
1
4
[[1. 1.]
 [1. 1.]]
20
[ 9 11]
[4 7 9]


In [91]:
# practice code1
# Create 2D Numpy array of students scores,compute class average,highest scorer, normalize score to 0-1 range
import numpy as n
a=n.array([[20,30,40,50],
           [70,30,50,46],
           [20,45,67,90]])
score=(n.sum(a,axis=1))
subavg=(n.sum(a,axis=0))
print(score)
print(subavg)
print(n.mean(a))
print(n.max(score))
print(n.mean(subavg))

[140 196 222]
[110 105 157 186]
46.5
222
139.5


In [94]:
# practice code2
# given arr=np.array([10,20,30,40,50]),write Numpy expressions to get all elements >25 and compute their sum
a=n.array([10,20,30,40,50])
print(a[a>25])
print(sum(a[a>25]))

[30 40 50]
120


In [ ]:
#Practice code3
# Give an example where a (3,1) array is added to a (4,1) array -what is the output shape??